name: 'Setup git publish action'
description: 'Setup git with an SSH key for pushing changes'
inputs:
  email:
    description: "Email to use with git"
    required: false
    default: 'bot@setup-git-publish-action'
  username:
    description: 'Username to use with git'
    required: false
    default: 'Github Action'
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
