name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: "Install"
      run: |
        npm install
    - name: "Prettier"
      run: |
        npm run format-check
    - name: "Lint"
      run: |
        npm run lint
    - name: "Test"
      run: |
        npm run test
    - name: "build"
      run: |
        npm run build
        npm run package

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: "Build action for test"
      run: |
        npm install
        npm run all
        git clean -fXd
    - name: Test executing the action
      uses: ./
      env:
        GIT_DEPLOY_KEY: not-a-real-key
      with:
        email: ${{ env.EMAIL_INPUT }}
        username: ${{ env.USERNAME_INPUT }}
    - name: Validate result
      run: |
        set -u

        DIRECTORIES=("$RUNNER_TEMP"/_github_home_*)

        [ "${#DIRECTORIES[@]}" -eq 1 ]

        KEY_DIRECTORY="${DIRECTORIES[0]}"

        cat "$RUNNER_TEMP/"*"/id_rsa"
        echo
        git config user.name
        git config user.email
        git remote get-url origin
        git config core.sshCommand
        grep '^github\.com' "$KEY_DIRECTORY/known_hosts"

        [[ "$(cat "$KEY_DIRECTORY/id_rsa")" == "not-a-real-key" ]]
        [[ "$(git config user.name)" == "${{ env.USERNAME_INPUT }}" ]]
        [[ "$(git config user.email)" == "${{ env.EMAIL_INPUT }}" ]]
        [[ "$(git remote get-url origin)" == "git@github.com:$GITHUB_REPOSITORY.git" ]]

        # Just check that it is altered from default
        [[ "$(git config core.sshCommand)" == *UserKnownHostsFile* ]]

  release:
    runs-on: ubuntu-22.04
    name: "Build and release action"
    needs: [build, test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          dry_run: true
          token: "${{ secrets.GITHUB_TOKEN }}"
